/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'product-categories': ProductCategory;
    'product-sizes': ProductSize;
    'product-tags': ProductTag;
    products: Product;
    orders: Order;
    'team-members': TeamMember;
    jobs: Job;
    applications: Application;
    pages: Page;
    'shipping-zones': ShippingZone;
    'email-templates': EmailTemplate;
    'dashboard-roles': DashboardRole;
    'analytics-events': AnalyticsEvent;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    'product-sizes': ProductSizesSelect<false> | ProductSizesSelect<true>;
    'product-tags': ProductTagsSelect<false> | ProductTagsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'shipping-zones': ShippingZonesSelect<false> | ShippingZonesSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    'dashboard-roles': DashboardRolesSelect<false> | DashboardRolesSelect<true>;
    'analytics-events': AnalyticsEventsSelect<false> | AnalyticsEventsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  /**
   * Dashboard role slug (must match a role in Dashboard → Roles, e.g. admin, hr, warehouse).
   */
  role: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  slug: string;
  label: string;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-sizes".
 */
export interface ProductSize {
  id: number;
  label: string;
  /**
   * Category slug this size belongs to (e.g. table_water).
   */
  categorySlug: string;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-tags".
 */
export interface ProductTag {
  id: number;
  slug: string;
  label: string;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Category slug (managed in Dashboard → Products → Categories).
   */
  category: string;
  name: string;
  size: string;
  price: number;
  description?: string | null;
  image?: (number | null) | Media;
  stock: number;
  /**
   * Optional product tags for search and filtering.
   */
  tags?: (number | ProductTag)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  customerName?: string | null;
  items: {
    product: number | Product;
    quantity: number;
    id?: string | null;
  }[];
  shipping: {
    fullName: string;
    email: string;
    phone: string;
    address: string;
    state?: string | null;
    /**
     * Local Government Area
     */
    lga?: string | null;
    /**
     * City, area, or landmark
     */
    city?: string | null;
    postalCode?: string | null;
  };
  /**
   * How the customer receives the order.
   */
  deliveryMode?: ('delivery' | 'pickup') | null;
  /**
   * Matched delivery location (shipping rule), captured at checkout.
   */
  shippingZone?: (number | null) | ShippingZone;
  /**
   * Computed delivery fee at the time of order.
   */
  shippingFee?: number | null;
  /**
   * Auto-linked customer account (created at checkout if needed).
   */
  customer?: (number | null) | User;
  total: number;
  status: 'pending' | 'paid' | 'processing' | 'delivered' | 'cancelled';
  /**
   * Paystack transaction reference
   */
  paystackReference?: string | null;
  paystackAccessCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Delivery locations and fees: match customer State / LGA / City on checkout (see each field).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-zones".
 */
export interface ShippingZone {
  id: number;
  /**
   * Label for this delivery location (e.g. "Lagos — mainland").
   */
  name: string;
  /**
   * Delivery fee (₦) when this location matches the customer address.
   */
  fee: number;
  /**
   * Optional notes shown in the admin (not displayed to customers).
   */
  description?: string | null;
  /**
   * Inactive locations are skipped when calculating fees.
   */
  isActive?: boolean | null;
  /**
   * When several locations match the same address tier (LGA, city, or state), the lowest number wins (default 100). Example: set "Lagos Island" to 10 and "All Lagos" to 50 so the island rate applies first.
   */
  priority?: number | null;
  /**
   * States where this fee applies (use official state names).
   */
  states?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional: Local Government Areas for a finer fee than state-wide. LGA match wins over city and state when the customer selects an LGA.
   */
  lgas?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * City / area names (as customers type them). City match is used after LGA, before state.
   */
  cities?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  position: string;
  department?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  sortOrder?: number | null;
  email?: string | null;
  linkedin?: string | null;
  twitter?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * Used in URLs, e.g. production-supervisor
   */
  slug: string;
  department: string;
  location: string;
  type: string;
  salaryRange?: string | null;
  description: string;
  requirements?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  postedDate?: string | null;
  status: 'active' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  job: number | Job;
  /**
   * Cached job title for quick listing
   */
  jobTitle?: string | null;
  fullName: string;
  email: string;
  phone: string;
  /**
   * Applicant reference (e.g. FZ-APP-2026-00042). Shown in confirmation emails.
   */
  applicationRef?: string | null;
  address?: string | null;
  educationHistory?:
    | {
        qualification: string;
        institution: string;
        fieldOfStudy?: string | null;
        startYear?: string | null;
        endYear?: string | null;
        grade?: string | null;
        id?: string | null;
      }[]
    | null;
  workHistory?:
    | {
        jobTitle: string;
        company: string;
        location?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        current?: boolean | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * CV professional summary
   */
  professionalSummary?: string | null;
  /**
   * Why the applicant wants this role
   */
  motivationStatement?: string | null;
  /**
   * Formatted education summary (auto-generated on apply)
   */
  education?: string | null;
  /**
   * Formatted experience summary
   */
  experience?: string | null;
  /**
   * Formatted cover letter summary
   */
  coverLetter?: string | null;
  resume?: (number | null) | Media;
  status: 'pending' | 'shortlisted' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL segment (e.g. about-us). Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  status?: ('draft' | 'published') | null;
  /**
   * Build the page from reusable sections.
   */
  layout?:
    | (
        | PageHeaderBlock
        | HeroBlock
        | ImageTextBlock
        | ProductsBlock
        | QualityBlock
        | SalesChannelsBlock
        | ContactBlock
        | FeatureGridBlock
        | CtaBannerBlock
        | RichTextBlock
      )[]
    | null;
  /**
   * Legacy rich-text body (used only when no sections are added).
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Comma-separated SEO keywords (optional). Falls back to site defaults.
   */
  keywords?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock".
 */
export interface PageHeaderBlock {
  icon?:
    | (
        | 'droplets'
        | 'flask'
        | 'award'
        | 'fileCheck'
        | 'checkCircle'
        | 'shield'
        | 'sparkles'
        | 'store'
        | 'warehouse'
        | 'factory'
        | 'truck'
        | 'phone'
        | 'mail'
        | 'mapPin'
        | 'clock'
        | 'star'
        | 'heart'
        | 'package'
        | 'users'
        | 'leaf'
        | 'zap'
        | 'globe'
      )
    | null;
  title: string;
  /**
   * Lead text, or a line like "Last updated: …"
   */
  subtitle?: string | null;
  align?: ('center' | 'left') | null;
  /**
   * Show a "Home / <title>" breadcrumb (left-aligned headers).
   */
  showBreadcrumb?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHeader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Small pill above the title
   */
  badge?: string | null;
  title: string;
  subtitle?: string | null;
  image?: (number | null) | Media;
  primaryCta?: {
    label?: string | null;
    /**
     * e.g. /order or https://…
     */
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * e.g. /order or https://…
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  heading?: string | null;
  body?: string | null;
  image?: (number | null) | Media;
  imagePosition?: ('right' | 'left') | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. /order or https://…
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductsBlock".
 */
export interface ProductsBlock {
  heading?: string | null;
  subheading?: string | null;
  items?:
    | {
        name: string;
        size?: string | null;
        description?: string | null;
        /**
         * Emoji or short label, e.g. 💧
         */
        icon?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  bannerHeading?: string | null;
  bannerBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'products';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QualityBlock".
 */
export interface QualityBlock {
  badge?: string | null;
  heading?: string | null;
  subheading?: string | null;
  certifications?:
    | {
        icon?:
          | (
              | 'droplets'
              | 'flask'
              | 'award'
              | 'fileCheck'
              | 'checkCircle'
              | 'shield'
              | 'sparkles'
              | 'store'
              | 'warehouse'
              | 'factory'
              | 'truck'
              | 'phone'
              | 'mail'
              | 'mapPin'
              | 'clock'
              | 'star'
              | 'heart'
              | 'package'
              | 'users'
              | 'leaf'
              | 'zap'
              | 'globe'
            )
          | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  processHeading?: string | null;
  steps?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  guaranteeTitle?: string | null;
  guaranteeBody?: string | null;
  /**
   * e.g. 100%
   */
  statValue?: string | null;
  statLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quality';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SalesChannelsBlock".
 */
export interface SalesChannelsBlock {
  heading?: string | null;
  subheading?: string | null;
  channels?:
    | {
        icon?:
          | (
              | 'droplets'
              | 'flask'
              | 'award'
              | 'fileCheck'
              | 'checkCircle'
              | 'shield'
              | 'sparkles'
              | 'store'
              | 'warehouse'
              | 'factory'
              | 'truck'
              | 'phone'
              | 'mail'
              | 'mapPin'
              | 'clock'
              | 'star'
              | 'heart'
              | 'package'
              | 'users'
              | 'leaf'
              | 'zap'
              | 'globe'
            )
          | null;
        title: string;
        description?: string | null;
        features?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaHeading?: string | null;
  ctaBody?: string | null;
  primaryCta?: {
    label?: string | null;
    /**
     * e.g. /order or https://…
     */
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * e.g. /order or https://…
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'salesChannels';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  heading?: string | null;
  subheading?: string | null;
  phone?: string | null;
  /**
   * e.g. tel:+234…
   */
  phoneHref?: string | null;
  email?: string | null;
  address?: string | null;
  hours?: string | null;
  whyTitle?: string | null;
  whyItems?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  heading?: string | null;
  subheading?: string | null;
  columns?: ('2' | '3' | '4') | null;
  features?:
    | {
        icon?:
          | (
              | 'droplets'
              | 'flask'
              | 'award'
              | 'fileCheck'
              | 'checkCircle'
              | 'shield'
              | 'sparkles'
              | 'store'
              | 'warehouse'
              | 'factory'
              | 'truck'
              | 'phone'
              | 'mail'
              | 'mapPin'
              | 'clock'
              | 'star'
              | 'heart'
              | 'package'
              | 'users'
              | 'leaf'
              | 'zap'
              | 'globe'
            )
          | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock".
 */
export interface CtaBannerBlock {
  heading?: string | null;
  body?: string | null;
  buttons?:
    | {
        label: string;
        href?: string | null;
        style?: ('primary' | 'outline') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  variant?: ('prose' | 'card') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  slug:
    | 'careers-application-received'
    | 'careers-application-shortlisted'
    | 'careers-application-approved'
    | 'careers-application-rejected'
    | 'careers-hr-new-application'
    | 'contact-lead-notification'
    | 'order-confirmation'
    | 'order-processing'
    | 'order-delivered'
    | 'order-cancelled'
    | 'order-staff-new-order';
  name: string;
  /**
   * Shown in the dashboard to explain when this email is sent.
   */
  description?: string | null;
  category: 'careers' | 'orders' | 'contact' | 'internal';
  layout: 'careers' | 'branded' | 'plain';
  /**
   * Use placeholders like {{jobTitle}} — see Variables help.
   */
  subject: string;
  /**
   * Plain-text version of the email.
   */
  textBody: string;
  /**
   * HTML body (inner content only; layout wrapper is applied automatically).
   */
  htmlBody: string;
  /**
   * Available placeholders for this template.
   */
  variablesHelp?: string | null;
  /**
   * When disabled, this email will not be sent.
   */
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboard-roles".
 */
export interface DashboardRole {
  id: number;
  /**
   * Matches user.role (e.g. admin, hr).
   */
  slug: string;
  name: string;
  description?: string | null;
  capabilities?:
    | {
        key:
          | 'dashboard.home'
          | 'analytics.view'
          | 'products.catalog'
          | 'products.categories'
          | 'products.sizes'
          | 'products.tags'
          | 'products.delete'
          | 'orders.view'
          | 'shipping.view'
          | 'team.view'
          | 'team.delete'
          | 'careers.manage'
          | 'applications.manage'
          | 'applications.delete'
          | 'organogram.view'
          | 'cms.view'
          | 'cms.pages.view'
          | 'cms.pages.create'
          | 'cms.pages.edit'
          | 'cms.pages.delete'
          | 'cms.pages.publish'
          | 'cms.home.manage'
          | 'cms.media.manage'
          | 'cms.seo.manage'
          | 'cms.header.manage'
          | 'cms.footer.manage'
          | 'settings.view'
          | 'email.templates'
          | 'email.templates.all'
          | 'audit.view'
          | 'diagnostics.view'
          | 'users.manage'
          | 'roles.manage'
          | 'system.backup';
        id?: string | null;
      }[]
    | null;
  /**
   * System roles cannot be deleted from the dashboard.
   */
  isSystem?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events".
 */
export interface AnalyticsEvent {
  id: number;
  type: 'pageview' | 'click' | 'resource_served' | 'web_vital';
  path?: string | null;
  referrer?: string | null;
  sessionId?: string | null;
  visitorId?: string | null;
  userId?: number | null;
  userEmail?: string | null;
  /**
   * Clicked resource label or href.
   */
  target?: string | null;
  /**
   * e.g. product, page, outbound, download, cta.
   */
  resourceType?: string | null;
  /**
   * Web Vital name (LCP, CLS, INP, FCP, TTFB).
   */
  metricName?: string | null;
  metricValue?: number | null;
  /**
   * good | needs-improvement | poor
   */
  rating?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: 'create' | 'update' | 'delete' | 'login' | 'logout';
  collectionSlug?: string | null;
  documentId?: string | null;
  /**
   * Human-readable label of the affected document.
   */
  title?: string | null;
  userId?: number | null;
  userEmail?: string | null;
  userRole?: string | null;
  /**
   * Changed fields (before/after) for updates, or the document snapshot.
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'product-sizes';
        value: number | ProductSize;
      } | null)
    | ({
        relationTo: 'product-tags';
        value: number | ProductTag;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'shipping-zones';
        value: number | ShippingZone;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: number | EmailTemplate;
      } | null)
    | ({
        relationTo: 'dashboard-roles';
        value: number | DashboardRole;
      } | null)
    | ({
        relationTo: 'analytics-events';
        value: number | AnalyticsEvent;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-sizes_select".
 */
export interface ProductSizesSelect<T extends boolean = true> {
  label?: T;
  categorySlug?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-tags_select".
 */
export interface ProductTagsSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  size?: T;
  price?: T;
  description?: T;
  image?: T;
  stock?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customerName?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  shipping?:
    | T
    | {
        fullName?: T;
        email?: T;
        phone?: T;
        address?: T;
        state?: T;
        lga?: T;
        city?: T;
        postalCode?: T;
      };
  deliveryMode?: T;
  shippingZone?: T;
  shippingFee?: T;
  customer?: T;
  total?: T;
  status?: T;
  paystackReference?: T;
  paystackAccessCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  department?: T;
  bio?: T;
  photo?: T;
  sortOrder?: T;
  email?: T;
  linkedin?: T;
  twitter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  department?: T;
  location?: T;
  type?: T;
  salaryRange?: T;
  description?: T;
  requirements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  postedDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  job?: T;
  jobTitle?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  applicationRef?: T;
  address?: T;
  educationHistory?:
    | T
    | {
        qualification?: T;
        institution?: T;
        fieldOfStudy?: T;
        startYear?: T;
        endYear?: T;
        grade?: T;
        id?: T;
      };
  workHistory?:
    | T
    | {
        jobTitle?: T;
        company?: T;
        location?: T;
        startDate?: T;
        endDate?: T;
        current?: T;
        description?: T;
        id?: T;
      };
  professionalSummary?: T;
  motivationStatement?: T;
  education?: T;
  experience?: T;
  coverLetter?: T;
  resume?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  layout?:
    | T
    | {
        pageHeader?: T | PageHeaderBlockSelect<T>;
        hero?: T | HeroBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        products?: T | ProductsBlockSelect<T>;
        quality?: T | QualityBlockSelect<T>;
        salesChannels?: T | SalesChannelsBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  body?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock_select".
 */
export interface PageHeaderBlockSelect<T extends boolean = true> {
  icon?: T;
  title?: T;
  subtitle?: T;
  align?: T;
  showBreadcrumb?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  subtitle?: T;
  image?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  image?: T;
  imagePosition?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductsBlock_select".
 */
export interface ProductsBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  items?:
    | T
    | {
        name?: T;
        size?: T;
        description?: T;
        icon?: T;
        href?: T;
        id?: T;
      };
  bannerHeading?: T;
  bannerBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QualityBlock_select".
 */
export interface QualityBlockSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  subheading?: T;
  certifications?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  processHeading?: T;
  steps?:
    | T
    | {
        value?: T;
        id?: T;
      };
  guaranteeTitle?: T;
  guaranteeBody?: T;
  statValue?: T;
  statLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SalesChannelsBlock_select".
 */
export interface SalesChannelsBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  channels?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        features?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  ctaHeading?: T;
  ctaBody?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  phone?: T;
  phoneHref?: T;
  email?: T;
  address?: T;
  hours?: T;
  whyTitle?: T;
  whyItems?:
    | T
    | {
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  columns?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock_select".
 */
export interface CtaBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  variant?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-zones_select".
 */
export interface ShippingZonesSelect<T extends boolean = true> {
  name?: T;
  fee?: T;
  description?: T;
  isActive?: T;
  priority?: T;
  states?:
    | T
    | {
        value?: T;
        id?: T;
      };
  lgas?:
    | T
    | {
        value?: T;
        id?: T;
      };
  cities?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  category?: T;
  layout?: T;
  subject?: T;
  textBody?: T;
  htmlBody?: T;
  variablesHelp?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboard-roles_select".
 */
export interface DashboardRolesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  capabilities?:
    | T
    | {
        key?: T;
        id?: T;
      };
  isSystem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events_select".
 */
export interface AnalyticsEventsSelect<T extends boolean = true> {
  type?: T;
  path?: T;
  referrer?: T;
  sessionId?: T;
  visitorId?: T;
  userId?: T;
  userEmail?: T;
  target?: T;
  resourceType?: T;
  metricName?: T;
  metricValue?: T;
  rating?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  title?: T;
  userId?: T;
  userEmail?: T;
  userRole?: T;
  changes?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  /**
   * Controls whether the "Quick Demo Login" card is shown on the /login page.
   */
  showLoginDemoCard?: boolean | null;
  logo?: (number | null) | Media;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  twitter?: string | null;
  linkedin?: string | null;
  defaultMetaTitle?: string | null;
  /**
   * Used in Google search snippets and social shares (150–160 characters ideal).
   */
  defaultMetaDescription?: string | null;
  /**
   * Comma-separated SEO keywords (e.g. Fizam, Fizam Table Water, table water Nigeria).
   */
  defaultKeywords?: string | null;
  /**
   * Google Search Console verification code (content value only, not the full meta tag).
   */
  googleSiteVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * The home page is built from these sections. Leave empty to use legacy fields below.
   */
  layout?:
    | (
        | PageHeaderBlock
        | HeroBlock
        | ImageTextBlock
        | ProductsBlock
        | QualityBlock
        | SalesChannelsBlock
        | ContactBlock
        | FeatureGridBlock
        | CtaBannerBlock
        | RichTextBlock
      )[]
    | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  aboutHeading?: string | null;
  aboutBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Text shown next to the logo.
   */
  brandName?: string | null;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional highlighted button (e.g. Order now).
   */
  ctaLabel?: string | null;
  ctaHref?: string | null;
  showLogin?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  about?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contact?: {
    phones?:
      | {
          label: string;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    email?: string | null;
    address?: string | null;
  };
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter';
        href: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Defaults to "© {year} Fizam Table Water. All rights reserved."
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  showLoginDemoCard?: T;
  logo?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  facebook?: T;
  instagram?: T;
  twitter?: T;
  linkedin?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultKeywords?: T;
  googleSiteVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        pageHeader?: T | PageHeaderBlockSelect<T>;
        hero?: T | HeroBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        products?: T | ProductsBlockSelect<T>;
        quality?: T | QualityBlockSelect<T>;
        salesChannels?: T | SalesChannelsBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  aboutHeading?: T;
  aboutBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  brandName?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  showLogin?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  about?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  contact?:
    | T
    | {
        phones?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        email?: T;
        address?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}